### ISSUE TITLE
Version overrides for nested BOMs does not seem to work

### ISSUE THREAD

**Issue by edudar-chwy** [austinarbor/version-catalog-generator#162]
I'm trying an example from README and overriding `jackson-bom` version provided by spring boot dependencies. 
```
propertyOverrides = mapOf("jackson-bom.version" to "2.17.0")
```
This does not work, and I don't see the code in `Generator` that would make this working as `loadBom` does not take `propertyOverrides` into account. It does override property from spring boot dependencies BOM, but has no impact on actual dependencies when used like `implementation(springLibs.jackson.jacksonAnnotations)`. This still resolves as 2.17.2.

```
propertyOverrides = mapOf("jackson-bom" to "2.17.0")
```
From the Javadoc, does not work either and seem to be a mistake in Javadoc as `.version` is required per above.

```
propertyOverrides = mapOf("jackson.version" to "2.17.0")
```
Works, but it requires knowing the exact version ID from nested BOM.

So, to correctly override jackson version one needs to have:
```
propertyOverrides = mapOf(
  "jackson-bom.version" to "2.17.0",
  "jackson.version" to "2.17.0",
)
```

It'd be great if overriding the BOM version would also override the dependencies it brings. I can see 
```
val (model, parentModel) = resolver.resolve(dep)
```
may handle that and resolve proper `model` and `parentModel` according to overrides

**Comment by austinarbor** [comment]
Thanks for pointing out that javadoc issue, I will fix that! 

Can you provide a settings.gradle.kts that reproduces the issue you are seeing? I see it working correctly on my side.

If, for example, I have

settings.gradle.kts:
```kotlin
dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
    versionCatalogs {
        generate("springLibs") {
            from("org.springframework.boot:spring-boot-dependencies:3.1.2")
            propertyOverrides = mapOf("jackson-bom.version" to "2.17.1")
            cacheEnabled = true
        }
    }
}
```
This produces a catalog with the entries below (I stripped out everything non-jackson related). The actual jackson-bom.version property in spring-boot-dependencies is 2.15.2

```toml
[versions]
  jacksonBom="2.17.1"
[libraries]
  [libraries.jackson-jacksonBom]
    group="com.fasterxml.jackson"
    name="jackson-bom"
    [libraries.jackson-jacksonBom.version]
      ref="jacksonBom"
  [libraries.jackson-jacksonAnnotations]
    group="com.fasterxml.jackson.core"
    name="jackson-annotations"
    version="2.17.1"
  [libraries.jackson-jacksonCore]
    group="com.fasterxml.jackson.core"
    name="jackson-core"
    version="2.17.1"
  [libraries.jackson-jacksonDatabind]
    group="com.fasterxml.jackson.core"
    name="jackson-databind"
    version="2.17.1"
  [libraries.jackson-jacksonDataformatAvro]
    group="com.fasterxml.jackson.dataformat"
    name="jackson-dataformat-avro"
    version="2.17.1"
  [libraries.jackson-jacksonDataformatCbor]
    group="com.fasterxml.jackson.dataformat"
    name="jackson-dataformat-cbor"
    version="2.17.1"
  [libraries.jackson-jacksonDataformatCsv]
    group="com.fasterxml.jackson.dataformat"
    name="jackson-dataformat-csv"
    version="2.17.1"
  [libraries.jackson-jacksonDataformatIon]
    group="com.fasterxml.jackson.dataformat"
    name="jackson-dataformat-ion"
    version="2.17.1"
  [libraries.jackson-jacksonDataformatProperties]
    group="com.fasterxml.jackson.dataformat"
    name="jackson-dataformat-properties"
    version="2.17.1"
  [libraries.jackson-jacksonDataformatProtobuf]
    group="com.fasterxml.jackson.dataformat"
    name="jackson-dataformat-protobuf"
    version="2.17.1"
  [libraries.jackson-jacksonDataformatSmile]
    group="com.fasterxml.jackson.dataformat"
    name="jackson-dataformat-smile"
    version="2.17.1"
  [libraries.jackson-jacksonDataformatToml]
    group="com.fasterxml.jackson.dataformat"
    name="jackson-dataformat-toml"
    version="2.17.1"
  [libraries.jackson-jacksonDataformatXml]
    group="com.fasterxml.jackson.dataformat"
    name="jackson-dataformat-xml"
    version="2.17.1"
  [libraries.jackson-jacksonDataformatYaml]
    group="com.fasterxml.jackson.dataformat"
    name="jackson-dataformat-yaml"
    version="2.17.1"
  [libraries.jackson-jacksonDatatypeEclipseCollections]
    group="com.fasterxml.jackson.datatype"
    name="jackson-datatype-eclipse-collections"
    version="2.17.1"
  [libraries.jackson-jacksonDatatypeGuava]
    group="com.fasterxml.jackson.datatype"
    name="jackson-datatype-guava"
    version="2.17.1"
  [libraries.jackson-jacksonDatatypeHibernate4]
    group="com.fasterxml.jackson.datatype"
    name="jackson-datatype-hibernate4"
    version="2.17.1"
  [libraries.jackson-jacksonDatatypeHibernate5]
    group="com.fasterxml.jackson.datatype"
    name="jackson-datatype-hibernate5"
    version="2.17.1"
  [libraries.jackson-jacksonDatatypeHibernate5Jakarta]
    group="com.fasterxml.jackson.datatype"
    name="jackson-datatype-hibernate5-jakarta"
    version="2.17.1"
  [libraries.jackson-jacksonDatatypeHibernate6]
    group="com.fasterxml.jackson.datatype"
    name="jackson-datatype-hibernate6"
    version="2.17.1"
  [libraries.jackson-jacksonDatatypeHppc]
    group="com.fasterxml.jackson.datatype"
    name="jackson-datatype-hppc"
    version="2.17.1"
  [libraries.jackson-jacksonDatatypeJakartaJsonp]
    group="com.fasterxml.jackson.datatype"
    name="jackson-datatype-jakarta-jsonp"
    version="2.17.1"
  [libraries.jackson-jacksonDatatypeJaxrs]
    group="com.fasterxml.jackson.datatype"
    name="jackson-datatype-jaxrs"
    version="2.17.1"
  [libraries.jackson-jacksonDatatypeJoda]
    group="com.fasterxml.jackson.datatype"
    name="jackson-datatype-joda"
    version="2.17.1"
  [libraries.jackson-jacksonDatatypeJodaMoney]
    group="com.fasterxml.jackson.datatype"
    name="jackson-datatype-joda-money"
    version="2.17.1"
  [libraries.jackson-jacksonDatatypeJdk8]
    group="com.fasterxml.jackson.datatype"
    name="jackson-datatype-jdk8"
    version="2.17.1"
  [libraries.jackson-jacksonDatatypeJsonOrg]
    group="com.fasterxml.jackson.datatype"
    name="jackson-datatype-json-org"
    version="2.17.1"
  [libraries.jackson-jacksonDatatypeJsr310]
    group="com.fasterxml.jackson.datatype"
    name="jackson-datatype-jsr310"
    version="2.17.1"
  [libraries.jackson-jacksonDatatypeJsr353]
    group="com.fasterxml.jackson.datatype"
    name="jackson-datatype-jsr353"
    version="2.17.1"
  [libraries.jackson-jacksonDatatypePcollections]
    group="com.fasterxml.jackson.datatype"
    name="jackson-datatype-pcollections"
    version="2.17.1"
  [libraries.jackson-jacksonJaxrsBase]
    group="com.fasterxml.jackson.jaxrs"
    name="jackson-jaxrs-base"
    version="2.17.1"
  [libraries.jackson-jacksonJaxrsCborProvider]
    group="com.fasterxml.jackson.jaxrs"
    name="jackson-jaxrs-cbor-provider"
    version="2.17.1"
  [libraries.jackson-jacksonJaxrsJsonProvider]
    group="com.fasterxml.jackson.jaxrs"
    name="jackson-jaxrs-json-provider"
    version="2.17.1"
  [libraries.jackson-jacksonJaxrsSmileProvider]
    group="com.fasterxml.jackson.jaxrs"
    name="jackson-jaxrs-smile-provider"
    version="2.17.1"
  [libraries.jackson-jacksonJaxrsXmlProvider]
    group="com.fasterxml.jackson.jaxrs"
    name="jackson-jaxrs-xml-provider"
    version="2.17.1"
  [libraries.jackson-jacksonJaxrsYamlProvider]
    group="com.fasterxml.jackson.jaxrs"
    name="jackson-jaxrs-yaml-provider"
    version="2.17.1"
  [libraries.jackson-jacksonJakartaRsBase]
    group="com.fasterxml.jackson.jakarta.rs"
    name="jackson-jakarta-rs-base"
    version="2.17.1"
  [libraries.jackson-jacksonJakartaRsCborProvider]
    group="com.fasterxml.jackson.jakarta.rs"
    name="jackson-jakarta-rs-cbor-provider"
    version="2.17.1"
  [libraries.jackson-jacksonJakartaRsJsonProvider]
    group="com.fasterxml.jackson.jakarta.rs"
    name="jackson-jakarta-rs-json-provider"
    version="2.17.1"
  [libraries.jackson-jacksonJakartaRsSmileProvider]
    group="com.fasterxml.jackson.jakarta.rs"
    name="jackson-jakarta-rs-smile-provider"
    version="2.17.1"
  [libraries.jackson-jacksonJakartaRsXmlProvider]
    group="com.fasterxml.jackson.jakarta.rs"
    name="jackson-jakarta-rs-xml-provider"
    version="2.17.1"
  [libraries.jackson-jacksonJakartaRsYamlProvider]
    group="com.fasterxml.jackson.jakarta.rs"
    name="jackson-jakarta-rs-yaml-provider"
    version="2.17.1"
  [libraries.jackson-jacksonJrAll]
    group="com.fasterxml.jackson.jr"
    name="jackson-jr-all"
    version="2.17.1"
  [libraries.jackson-jacksonJrAnnotationSupport]
    group="com.fasterxml.jackson.jr"
    name="jackson-jr-annotation-support"
    version="2.17.1"
  [libraries.jackson-jacksonJrExtensionJavatime]
    group="com.fasterxml.jackson.jr"
    name="jackson-jr-extension-javatime"
    version="2.17.1"
  [libraries.jackson-jacksonJrObjects]
    group="com.fasterxml.jackson.jr"
    name="jackson-jr-objects"
    version="2.17.1"
  [libraries.jackson-jacksonJrRetrofit2]
    group="com.fasterxml.jackson.jr"
    name="jackson-jr-retrofit2"
    version="2.17.1"
  [libraries.jackson-jacksonJrStree]
    group="com.fasterxml.jackson.jr"
    name="jackson-jr-stree"
    version="2.17.1"
  [libraries.jackson-jacksonModuleAfterburner]
    group="com.fasterxml.jackson.module"
    name="jackson-module-afterburner"
    version="2.17.1"
  [libraries.jackson-jacksonModuleAndroidRecord]
    group="com.fasterxml.jackson.module"
    name="jackson-module-android-record"
    version="2.17.1"
  [libraries.jackson-jacksonModuleBlackbird]
    group="com.fasterxml.jackson.module"
    name="jackson-module-blackbird"
    version="2.17.1"
  [libraries.jackson-jacksonModuleGuice]
    group="com.fasterxml.jackson.module"
    name="jackson-module-guice"
    version="2.17.1"
  [libraries.jackson-jacksonModuleGuice7]
    group="com.fasterxml.jackson.module"
    name="jackson-module-guice7"
    version="2.17.1"
  [libraries.jackson-jacksonModuleJaxbAnnotations]
    group="com.fasterxml.jackson.module"
    name="jackson-module-jaxb-annotations"
    version="2.17.1"
  [libraries.jackson-jacksonModuleJakartaXmlbindAnnotations]
    group="com.fasterxml.jackson.module"
    name="jackson-module-jakarta-xmlbind-annotations"
    version="2.17.1"
  [libraries.jackson-jacksonModuleJsonschema]
    group="com.fasterxml.jackson.module"
    name="jackson-module-jsonSchema"
    version="2.17.1"
  [libraries.jackson-jacksonModuleJsonschemaJakarta]
    group="com.fasterxml.jackson.module"
    name="jackson-module-jsonSchema-jakarta"
    version="2.17.1"
  [libraries.jackson-jacksonModuleMrbean]
    group="com.fasterxml.jackson.module"
    name="jackson-module-mrbean"
    version="2.17.1"
  [libraries.jackson-jacksonModuleNoCtorDeser]
    group="com.fasterxml.jackson.module"
    name="jackson-module-no-ctor-deser"
    version="2.17.1"
  [libraries.jackson-jacksonModuleOsgi]
    group="com.fasterxml.jackson.module"
    name="jackson-module-osgi"
    version="2.17.1"
  [libraries.jackson-jacksonModuleParameterNames]
    group="com.fasterxml.jackson.module"
    name="jackson-module-parameter-names"
    version="2.17.1"
  [libraries.jackson-jacksonModuleParanamer]
    group="com.fasterxml.jackson.module"
    name="jackson-module-paranamer"
    version="2.17.1"
  [libraries.jackson-jacksonModuleKotlin]
    group="com.fasterxml.jackson.module"
    name="jackson-module-kotlin"
    version="2.17.1"
  [libraries.jackson-jacksonModuleScala211]
    group="com.fasterxml.jackson.module"
    name="jackson-module-scala_2.11"
    version="2.17.1"
  [libraries.jackson-jacksonModuleScala212]
    group="com.fasterxml.jackson.module"
    name="jackson-module-scala_2.12"
    version="2.17.1"
  [libraries.jackson-jacksonModuleScala213]
    group="com.fasterxml.jackson.module"
    name="jackson-module-scala_2.13"
    version="2.17.1"
  [libraries.jackson-jacksonModuleScala3]
    group="com.fasterxml.jackson.module"
    name="jackson-module-scala_3"
    version="2.17.1"
```

Likewise, if I look at the external libraries brought in, you can see it's using the correct (overridden) version

build.gradle.kts:
```kotlin
plugins {
    kotlin("jvm") version "2.0.21"
}

dependencies {
    implementation(springLibs.jackson.jacksonAnnotations)
}
```
<img width="434" alt="image" src="https://github.com/user-attachments/assets/000678ae-852f-41e8-baca-434650e37002">
