### ISSUE TITLE
Allow creating a catalog from multiple bom aliases

### ISSUE THREAD

**Issue by stack-smash** [austinarbor/version-catalog-generator#163]
Hi, first of all, thank you for creating this plugin. It has been extremely helpful for my work. 

However, I was wondering if it is possible to create a catalog using multiple bom aliases from possibly the same toml file, and if not, can such a feature be added? 

I guess one way to do this is allow a `Set` of `libraryAlias` in the `TomlConfig` and pass this `Set` to the `ArrayDequeue` when loading the boms? 

For example,  something like 

```kotlin
// settings.gradle.kts
dependencyResolutionManagement {
    versionCatalogs {
        generate("lib1") {
            from(toml("jacksonBom", "awsBom", "reactorBom")) // aliases define in ./gradle/libs.versions.toml
        }

        generate("lib2") {
            from {
                toml {
                     libraryAliases = listOf("jacksonBom", "awsBom",  "reactorBom") 
                     file = file("./gradle/boms.versions.toml") // non-standard toml file name
                }
            }
        }
    }
}
```

[This project](https://github.com/F43nd1r/bomVersionCatalog) (that was deprecated in favor of yours) seems to support something similar (aliases matching a regex are added to the same catalog). 

The thing is that I have a centralized catalog where boms can be added and making one catalog per bom can generate too many catalogs.

**Comment by austinarbor** [comment]
@stack-smash I am a fan of this idea and on the _surface_ would be trivial to implement. However, it does pose some interesting problems.

- how would property overrides work if multiple BOMs contain the same property? what if that leads to an invalid version in one of the catalogs?
  - do property overrides need to be made BOM-specific?
  - if BOM specific, we may still need a global override ability to prevent repetitive replacements
- what if the BOMs specify the same dependencies? current logic (if we used the same logic as the nested BOM support) would be to only use the first found

**Comment by stack-smash** [comment]
Well, if we can define multiple bom aliases in a single catalog, then I believe `propertyOverrides` can be done away with. Users can simply define the their preferred version of a bom in the toml file and add that alias to the `from` method. 

So, instead of doing something like this
```toml
[libraries]
springBootDeps = { module = "org.springframework.boot:spring-boot-dependencies", version = "3.4.0" }
```

```kotlin
// settings.gradle.kts
dependencyResolutionManagement {
    versionCatalogs {
        generate("springLibs") {
          from(toml("springBootDeps")) // provides jackson 2.18.1
          propertyOverrides = mapOf(
              "jackson-bom.version" to "2.18.2"
          )
        }
    }
}
```

you could something like this
```toml
// libs.versions.toml
[libraries]
springBootDeps = { module = "org.springframework.boot:spring-boot-dependencies", version = "3.4.0" }
jacksonBom = { module = "com.fasterxml.jackson:jackson-bom", version = "2.18.2" }
```
```kotlin
// settings.gradle.kts
dependencyResolutionManagement {
    versionCatalogs {
        generate("boms") {
            from(toml("springBootDeps", "jacksonBom")) // this should provide the version of jackson you want
        }
    }
}
```
