### ISSUE TITLE
Any way to make the linter realize that the entry is NOT "unused"?

### ISSUE THREAD

**Issue by kohenkatz** [austinarbor/version-catalog-generator#172]
# Simple example

## `libs.versions.toml`

```toml
[versions]
compose-bom = "2024.12.01"

[libraries]
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
```

## `settings.gradle.kts`

```kotlin
plugins {
    id("dev.aga.gradle.version-catalog-generator") version("2.1.2")
}

dependencyResolutionManagement {
    versionCatalogs {
        generate("composeLibs") {
            from(toml("compose-bom"))
            aliasPrefixGenerator = GeneratorConfig.NO_PREFIX
            cacheEnabled = true
        }
    }
}
```

In Android Studio, the `libraries` line for `compose-bom` is greyed out, with tooltip text:

> Dependency alias 'compose-bom' is not used in build scripts

I'm worried this will cause another developer to think it is safe to remove this line (which is obviously not the case).

I tried to add `#noinspection UnusedVersionCatalogEntry` above the `compose-bom` line, but that doesn't seem to help.

Is there any way to indicate to the linter that this line is used by the plugin?
